# Generated by Django 3.0.5 on 2020-05-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='profilePics')),
                ('dob', models.DateField()),
                ('friendPoints', models.IntegerField(default=0, editable=False)),
            ],
        ),
    ]
