# Generated by Django 3.0.5 on 2020-05-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='amount_raised',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='user_info',
            name='event_created',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='user_info',
            name='friends',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='user_info',
            name='join_date',
            field=models.DateField(default='2020-05-28'),
        ),
        migrations.AddField(
            model_name='user_info',
            name='likes',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
