# Generated by Django 3.0.5 on 2020-05-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationWeb', '0003_auto_20200528_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='join_date',
            field=models.CharField(max_length=20),
        ),
    ]
