# Generated by Django 3.0.5 on 2020-05-28 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donationWeb', '0005_auto_20200528_1948'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_info',
            new_name='more_info',
        ),
    ]
