# Generated by Django 3.0.5 on 2020-05-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donationWeb', '0006_auto_20200528_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='more_info',
            name='join_date',
        ),
    ]
