# Generated by Django 3.0.5 on 2020-05-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationWeb', '0007_remove_more_info_join_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='more_info',
            name='like_persons',
            field=models.TextField(default="None"),
        ),
    ]
