# Generated by Django 3.0.5 on 2020-05-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationWeb', '0008_more_info_like_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='more_info',
            name='like_persons',
            field=models.TextField(default='0'),
        ),
    ]
