# Generated by Django 3.0.5 on 2020-05-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationWeb', '0009_auto_20200528_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='more_info',
            name='like_persons',
            field=models.CharField(default='0', max_length=5000),
        ),
    ]
