# Generated by Django 3.0.5 on 2020-05-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationWeb', '0010_auto_20200528_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='credit_card',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_id', models.IntegerField()),
                ('owner_name', models.CharField(max_length=30)),
                ('owner_surname', models.CharField(max_length=30)),
                ('exp_date', models.DateField()),
                ('cvv_number', models.IntegerField()),
                ('optional_card_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='friend_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_1', models.IntegerField()),
                ('user_2', models.IntegerField()),
                ('isAccepted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_id', models.IntegerField()),
                ('receiver_id', models.IntegerField()),
                ('msg', models.CharField(max_length=600)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('isRead', models.BooleanField()),
            ],
        ),
    ]
