# Generated by Django 3.0.5 on 2020-05-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationWeb', '0011_credit_card_friend_list_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='more_info',
            name='all_friends',
            field=models.CharField(default='0', max_length=5000),
        ),
    ]
