# Generated by Django 3.0.5 on 2020-05-29 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationWeb', '0012_more_info_all_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend_list',
            name='isRead',
            field=models.BooleanField(default=0),
        ),
    ]
