# Generated by Django 3.0.5 on 2020-05-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationWeb', '0013_friend_list_isread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend_list',
            name='isRead',
        ),
        migrations.AlterField(
            model_name='friend_list',
            name='isAccepted',
            field=models.BooleanField(default=0),
        ),
    ]
