# Generated by Django 3.0.5 on 2020-05-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationWeb', '0014_auto_20200529_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend_list',
            old_name='user_1',
            new_name='acceptor',
        ),
        migrations.RenameField(
            model_name='friend_list',
            old_name='user_2',
            new_name='sender',
        ),
        migrations.AddField(
            model_name='friend_list',
            name='isRead',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='friend_list',
            name='sender_image',
            field=models.CharField(default="None", max_length=300),
        ),
        migrations.AddField(
            model_name='more_info',
            name='isOnline',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='notifications',
            name='sender_image',
            field=models.CharField(default='qwerty', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notifications',
            name='isRead',
            field=models.BooleanField(default=0),
        ),
    ]
