# Generated by Django 3.0.5 on 2020-05-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationWeb', '0015_auto_20200529_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend_list',
            name='msg',
            field=models.CharField(default='None', max_length=800),
        ),
    ]
