# Generated by Django 3.0.5 on 2020-05-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationWeb', '0016_friend_list_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='more_info',
            name='friendPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='more_info',
            name='friends',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='more_info',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
