# Generated by Django 3.0.5 on 2020-05-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationWeb', '0017_auto_20200529_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='more_info',
            name='is_credit_card_added',
            field=models.BooleanField(default=0),
        ),
    ]
