# Generated by Django 3.0.5 on 2020-05-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationWeb', '0019_credit_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit_cards',
            name='total_credit',
            field=models.IntegerField(default=5000),
        ),
    ]
