# Generated by Django 3.0.5 on 2020-05-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationWeb', '0020_credit_cards_total_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='events')),
                ('host_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('starting_date', models.DateField()),
                ('due_date', models.DateField()),
                ('current_amount', models.IntegerField(default=0)),
                ('total_participants', models.IntegerField(default=0)),
                ('target_amount', models.IntegerField(default=0)),
            ],
        ),
    ]
