# Generated by Django 3.0.5 on 2020-06-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationWeb', '0022_auto_20200531_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='donation_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.IntegerField()),
                ('donor_id', models.IntegerField()),
                ('credit_card_id', models.IntegerField()),
                ('donation_date', models.DateField()),
                ('donation_amount', models.IntegerField()),
            ],
        ),
    ]
