# Generated by Django 3.0.5 on 2020-06-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationWeb', '0024_events_remaining_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='isCompleted',
            field=models.BooleanField(default=0),
        ),
    ]
