# Generated by Django 3.0.7 on 2020-06-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationWeb', '0026_events_is_amount_collected_by_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='excursions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('excursions_name', models.CharField(max_length=70)),
                ('excursions_image', models.ImageField(upload_to='excursions_pics')),
                ('excursions_type', models.CharField(max_length=100)),
                ('excursions_description', models.TextField()),
                ('amount_per_person', models.FloatField()),
                ('excursions_date', models.DateField()),
                ('excursions_departure_time', models.TimeField()),
                ('excursions_return_date', models.DateField()),
                ('excursions_return_time', models.TimeField()),
                ('excursions_ratings', models.FloatField()),
                ('excursions_minimum_people', models.IntegerField()),
                ('excursions_maximum_people', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='credit_card',
        ),
        migrations.DeleteModel(
            name='credit_cards',
        ),
        migrations.DeleteModel(
            name='donation_details',
        ),
        migrations.DeleteModel(
            name='events',
        ),
        migrations.DeleteModel(
            name='friend_list',
        ),
        migrations.DeleteModel(
            name='more_info',
        ),
        migrations.DeleteModel(
            name='notifications',
        ),
    ]
