# Generated by Django 3.0.7 on 2020-06-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationWeb', '0027_auto_20200630_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursions',
            name='excursions_type',
            field=models.CharField(choices=[('adventure', 'adventure'), ('activity', 'activity'), ('relax', 'relax'), ('city discovery', 'city discovery')], max_length=100),
        ),
    ]
