# Generated by Django 3.0.7 on 2020-07-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationWeb', '0029_excursions_excursions_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_confirmation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code_hash', models.CharField(max_length=32)),
                ('is_verified', models.BooleanField()),
            ],
        ),
    ]
