# Generated by Django 3.0.7 on 2020-07-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationWeb', '0031_profile_pics'),
    ]

    operations = [
        migrations.CreateModel(
            name='availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_excursion', models.CharField(choices=[('1', 'Withlocals Virtual Aperitivo Lesson with a Roman Local'), ('2', 'Magic of Film Themed Virtual Tour of London'), ('3', 'Withlocals Virtual Aperitivo Lesson with a Roman Local'), ('4', 'Magic of Film Themed Virtual Tour of London')], max_length=255)),
                ('availability_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('return_date', models.DateField()),
                ('return_time', models.TimeField()),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='excursions',
            name='excursions_date',
        ),
        migrations.RemoveField(
            model_name='excursions',
            name='excursions_departure_time',
        ),
        migrations.RemoveField(
            model_name='excursions',
            name='excursions_return_date',
        ),
        migrations.RemoveField(
            model_name='excursions',
            name='excursions_return_time',
        ),
    ]
