# Generated by Django 3.0.7 on 2020-07-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationWeb', '0032_auto_20200701_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='is_completed',
            new_name='trip_completed',
        ),
        migrations.AddField(
            model_name='availability',
            name='departure_point',
            field=models.CharField(default='ABC street', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availability',
            name='return_point',
            field=models.CharField(default='ABC street', max_length=255),
            preserve_default=False,
        ),
    ]
