# Generated by Django 3.0.3 on 2020-07-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationWeb', '0035_auto_20200704_0506'),
    ]

    operations = [
        migrations.CreateModel(
            name='ex_reviews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author_id', models.IntegerField()),
                ('author_name', models.CharField(max_length=50)),
                ('author_picture', models.CharField(max_length=150)),
                ('review_star', models.IntegerField()),
                ('review_msg', models.TextField()),
                ('event_id', models.IntegerField()),
            ],
        ),
    ]
