# Generated by Django 3.0.3 on 2020-07-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationWeb', '0036_ex_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='ex_reviews',
            name='date',
            field=models.DateField(default='2020-07-04'),
        ),
    ]
