# Generated by Django 2.1.15 on 2020-07-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationWeb', '0037_ex_reviews_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_details',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking_details',
            name='current_date',
            field=models.DateField(default='2020-07-06'),
        ),
        migrations.AlterField(
            model_name='ex_reviews',
            name='date',
            field=models.DateField(default='2020-07-06'),
        ),
    ]
